examples/ruby/rails3/config/routes.rb
Rails3::Application.routes.draw do

  resources :puns do
    member do
      post 'up_vote'
    end
  end

  root :to => 'application#index'

end

examples/ruby/rails3/app/models/pun.rb
class Pun < ActiveRecord::Base
  attr_accessible :description, :rating, :image

  mount_uploader :image, ImageUploader

  validates :description,  :presence => true
end

examples/ruby/rails3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def index
    @puns = Pun.all
    @title = "Pun Trackr"
    @quote = "<p>Pun Trackr will revolutionize the pun-guin industry. <span class=\"muted small\">(not)</span></p>"

    respond_to do |format|
      format.html  # index.html.erb
    end
  end
end

examples/ruby/rails3/app/controllers/puns_controller.rb
class PunsController < ApplicationController

  def new
    @pun = Pun.new
    @title = "Add puns"
    @quote = "<p>Add a pun in your breakfast. </p><small>Anonymous</small>"

    respond_to do |format|
      format.html  # new.html.erb
    end
  end

  def create
    @pun = Pun.new(params[:pun])
    @title = "Add puns"
    @quote = "<p>Add a pun in your breakfast. </p><small>Anonymous</small>"

    respond_to do |format|
      if @pun.save
        flash[:message] = 'Your Pun is a success !'
        format.html  { redirect_to :action => "new" }
      else
        format.html  { render :action => "new" }
      end
    end
  end

  def up_vote
    @pun = Pun.find(params[:id])

    respond_to do |format|
      @pun.update_attribute('rating', @pun.rating + params[:rate].to_i)

      format.html  { redirect_to :controller => "application", :action => "index" }
    end
  end

  def destroy
    @pun = Pun.find(params[:id])
    @pun.destroy

    respond_to do |format|
      format.html { redirect_to :controller => "application", :action => "index" }
    end
  end
end

examples/ruby/rails3/app/helpers/pun_helper.rb
module PunHelper
end

examples/ruby/rails3/app/views/application/index.html.erb
<% if @puns.empty? %>
<div class="alert">
    <strong>Hmmm!</strong> Nothing yet.
</div>
<% else %>

  <table class="table table-striped">
  <% @puns.each do |pun| %>
      <tr>
          <td>
              Texte:<br /> <em><%= pun.description %></em>
          </td>
          <td>
              <img class="thumbnail" src=<% if pun.image.blank? %> "http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" <% else %> "<%= pun.image.url %>" <% end %>>
          </td>
          <td>
              <div>
                <%= link_to up_vote_pun_path(:id => pun.id, :rate => 1), :method => :post do %> <i class="icon-chevron-up"></i> <% end %>
                <%= link_to up_vote_pun_path(:id => pun.id, :rate => -1), :method => :post do %> <i class="icon-chevron-down"></i> <% end %>

                <% if pun.rating.to_i > 0 %>
                  <span class="badge badge-success"><%= pun.rating %></span>
                <% else %>
                  <span class="badge badge-warning"><%= pun.rating %></span>
                <% end %>
              </div>

              <br />
            <%= link_to "Delete", pun_path(pun.id), :method => :delete %> <i class="icon-trash">
          </td>
      </tr>
  <% end %>
<% end %>

examples/ruby/rails3/app/views/common/_nav.html.erb
<div class="navbar">
    <div class="navbar-inner">
        <%= link_to "Pun Trackr", {:controller => "application", :action => "index"}, :class => "brand" %>
        <ul class="nav nav-pills">
            <li><%= link_to "Add Puns", new_pun_path, :id => 'add-puns'  %></li>
        </ul>
    </div>
</div>

examples/ruby/rails3/app/views/common/_scripts.html.erb
<%= javascript_include_tag "application" %>
<%= javascript_include_tag "bootstrap.min" %>

examples/ruby/rails3/app/views/common/_styles.html.erb
<%= stylesheet_link_tag    "bootstrap", :media => "all" %>
<%= stylesheet_link_tag    "bootstrap-responsive", :media => "all" %>
<%= stylesheet_link_tag    "jasny-bootstrap.min", :media => "all" %>
<%= stylesheet_link_tag    "jasny-bootstrap-responsive.min", :media => "all" %>
<%= stylesheet_link_tag    "custom", :media => "all" %>
<%= stylesheet_link_tag    "pun", :media => "all" %>

examples/ruby/rails3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title><%= @title %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="track the best puns">
  <meta name="author" content="Aurélien Thieriot">

  <%= render 'common/styles' %>
  <%= render 'common/scripts' %>

  <%= csrf_meta_tag %>
</head>
<body>

<div class="container-fluid">

    <%= render 'common/nav' %>

    <div class="row-fluid">
        <div class="offset1 span10">
            <div class="hero-unit">
                <h1><%= @title %></h1>

                <blockquote>
                    <%= raw(@quote) %>
                </blockquote>
            </div>

            <%= yield %>
        </div>
    </div>
</div>
</body>
</html>

examples/ruby/rails3/app/views/puns/new.html.erb
<%= form_for(@pun, :multipart => true) do |f| %>

  <% if flash[:message] %>
    <div class="alert alert-success"><%= flash[:message] %></div>
  <% end %>

  <div class="well">
  <% if @pun.errors.any? %>
    <div id="errorExplanation">
      <div class="alert alert-error"><%= pluralize(@pun.errors.count, "error") %> prohibited this post from being saved:</div>
      <% @pun.errors.full_messages.each do |msg| %>
        <div class="alert alert-error"><%= msg %></div>
      <% end %>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 3, :cols => 50 %>
  </div>

  <div class="fileupload fileupload-new" data-provides="fileupload">
    <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" /></div>
    <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
    <div>
      <span class="btn btn-file"><span class="fileupload-new">Select image</span><span class="fileupload-exists">Change</span><%= f.file_field :image %></span>
      <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
    </div>
  </div>

  <%= f.submit "Add", :class => "form-actions btn btn-primary" %>
  </div>
<% end %>